import * as THREE from 'three';
import {openInspection} from '/inspection.js';
import {OrbitControls} from '/vendor/OrbitControls.js';
const $=id=>document.getElementById(id);
export function setupMap(){
 const view=$('mapViewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#07121e');scene.fog=new THREE.FogExp2('#07121e',.00014);
 const camera=new THREE.PerspectiveCamera(43,1,1,20000);camera.up.set(0,0,1);
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.appendChild(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.AmbientLight(0xbeddf5,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(400,-800,1800);scene.add(light);
 const grid=new THREE.GridHelper(6000,100,0x183446,0x0c2232);grid.rotation.x=Math.PI/2;grid.position.set(1600,0,-18);scene.add(grid);
 let geometryGroup=new THREE.Group(),route=null,length=0,progress=.12,running=false,follow=false,flat=false,last=performance.now(),demo=true,stations=[];scene.add(geometryGroup);
 const markerLayer=document.createElement('div');markerLayer.className='map-marker-layer';view.append(markerLayer);
 const eventPanel=document.createElement('section');eventPanel.className='map-events';eventPanel.innerHTML='<h3>Обнаружения на схеме</h3><p class="sub">Красные точки — сохранённые тревожные кадры. Позиции условные: это демонстрация, а не место обнаружения. Отмеченные ложными тревоги скрыты; остальные ещё требуют проверки.</p><button class="refresh-map-events">Обновить отметки</button><div class="map-event-list" role="status"></div>';$('mapStatus').after(eventPanel);
 let events=[],markers=[],eventRequest=0;
 function rebuildMarkers(){markerLayer.replaceChildren();markers=[];const list=eventPanel.querySelector('.map-event-list');list.replaceChildren();if(!demo||!route){list.textContent='Отметки доступны на демонстрационной схеме. Для загруженной карты координаты событий неизвестны.';return;}if(!events.length){list.textContent='В журнале пока нет тревог с доступным облаком.';return;}events.forEach((event,index)=>{const title=`${event.source} · ${event.frame===null?'поток':'кадр '+event.frame} · ${event.distance.toFixed(1)} м`;const marker=document.createElement('button');marker.className='map-event-marker';marker.textContent=index+1;marker.title=title;marker.setAttribute('aria-label','Открыть облако: '+title);marker.onclick=()=>openInspection(event.id);markerLayer.append(marker);markers.push({element:marker,position:route.getPoint(.12+.76*(index+.5)/events.length)});const button=document.createElement('button'),number=document.createElement('b'),label=document.createElement('span');number.textContent=`● ${index+1}  `;label.textContent=title+(event.verdict==='false'?' · отмечено ложным':' · '+event.group_count+' тревожных кадров');button.append(number,label);button.onclick=()=>openInspection(event.id);list.append(button);});}
 async function refreshEvents(){const request=++eventRequest;try{const r=await fetch('/api/map/events');if(!r.ok)throw Error('Не удалось загрузить журнал');const data=await r.json();if(request!==eventRequest)return;events=data.events;rebuildMarkers();}catch(e){eventPanel.querySelector('.map-event-list').textContent=e.message;}}
 function updateMarkers(){for(const marker of markers){const p=marker.position.clone().project(camera);const visible=p.z>=-1&&p.z<=1&&Math.abs(p.x)<1&&Math.abs(p.y)<1;marker.element.hidden=!visible;marker.element.style.left=(p.x+1)*view.clientWidth/2+'px';marker.element.style.top=(1-p.y)*view.clientHeight/2+'px';}}
 eventPanel.querySelector('button').onclick=refreshEvents;window.addEventListener('metro-map-refresh',refreshEvents);
 const train=new THREE.Group();scene.add(train);
 for(let i=0;i<3;i++){const body=new THREE.Mesh(new THREE.BoxGeometry(22,9,8),new THREE.MeshStandardMaterial({color:i===0?0xe9f4fa:0x89bacb,metalness:.35,roughness:.35}));body.position.set(-i*25,0,5);train.add(body);const roof=new THREE.Mesh(new THREE.BoxGeometry(17,8,1),new THREE.MeshStandardMaterial({color:0x14c8ac,emissive:0x146f62}));roof.position.set(-i*25,0,9.5);train.add(roof);}
 const halo=new THREE.Mesh(new THREE.RingGeometry(30,35,48),new THREE.MeshBasicMaterial({color:0x59efc9,side:THREE.DoubleSide,transparent:true,opacity:.65}));halo.position.z=.5;train.add(halo);
 function disposeGroup(){geometryGroup.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});scene.remove(geometryGroup);geometryGroup=new THREE.Group();scene.add(geometryGroup);}
 function tube(points,radius,color,opacity=1){const curve=new THREE.CatmullRomCurve3(points);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.min(1200,points.length*2),radius,6,false),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.65,transparent:opacity<1,opacity,roughness:.8}));geometryGroup.add(mesh);}
 function label(text,point){const c=document.createElement('canvas');c.width=768;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#0b2034';ctx.fillRect(0,0,768,128);ctx.strokeStyle='#2b6174';ctx.strokeRect(2,2,764,124);ctx.fillStyle='#c4ecf6';ctx.font='500 46px Segoe UI';ctx.textAlign='center';ctx.fillText(text,384,78);const tex=new THREE.CanvasTexture(c);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false}));sprite.position.copy(point).add(new THREE.Vector3(0,105,100));sprite.scale.set(470,78,1);geometryGroup.add(sprite);}
 function fit(){const box=new THREE.Box3().setFromObject(geometryGroup);if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());const span=Math.max(size.x,size.y,100);controls.target.copy(center);camera.position.copy(center).add(flat?new THREE.Vector3(0,-.1,span*.95):new THREE.Vector3(span*.12,-span*.62,span*.64));controls.update();}
 function build(points,isDemo){disposeGroup();demo=isDemo;stations=[];route=new THREE.CurvePath();for(let i=1;i<points.length;i++)route.add(new THREE.LineCurve3(points[i-1],points[i]));length=route.getLength();const samples=route.getSpacedPoints(Math.min(1000,Math.ceil(length/4)));tube(samples,13,0x123f53,.9);tube(samples,7.5,0x31a49c,.9);
  for(const side of [-1,1]){const rails=samples.map((p,i)=>{const t=route.getTangent(i/(samples.length-1)),n=new THREE.Vector3(-t.y,t.x,0).normalize();return p.clone().addScaledVector(n,side*3.6).add(new THREE.Vector3(0,0,1.6));});tube(rails,1.4,0xa5ece1);}
  const ties=[];for(let s=0;s<length;s+=12){const p=route.getPoint(s/length),t=route.getTangent(s/length),n=new THREE.Vector3(-t.y,t.x,0).normalize();ties.push(p.clone().addScaledVector(n,-7),p.clone().addScaledVector(n,7));}geometryGroup.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(ties),new THREE.LineBasicMaterial({color:0x346476,transparent:true,opacity:.8})));
  if(demo){stations=[{p:.02,name:'Депо Северное'},{p:.36,name:'Станция Парк'},{p:.71,name:'Технологическая'},{p:.98,name:'Южная'}];for(const station of stations){const p=route.getPoint(station.p),t=route.getTangent(station.p);const block=new THREE.Mesh(new THREE.BoxGeometry(135,45,5),new THREE.MeshStandardMaterial({color:0x194457,emissive:0x0c2639}));block.position.copy(p).add(new THREE.Vector3(0,0,-1));block.rotation.z=Math.atan2(t.y,t.x);geometryGroup.add(block);const ring=new THREE.Mesh(new THREE.RingGeometry(30,34,64),new THREE.MeshBasicMaterial({color:0x56d8bf,side:THREE.DoubleSide}));ring.position.copy(p).add(new THREE.Vector3(0,0,3));geometryGroup.add(ring);label(station.name,p);}}
  train.visible=true;progress=.12;running=false;$('demoPlay').textContent='▶ Запустить пример';$('demoPlay').disabled=false;$('mapProgress').disabled=false;$('mapBadge').textContent=demo?'ДЕМОНСТРАЦИЯ · НЕ ЛОКАЛИЗАЦИЯ':'КАРТА ЗАГРУЖЕНА · ПОЗИЦИЯ УСЛОВНАЯ';$('mapCaption').textContent=demo?'Учебная схема метро · координаты условные · не связана с LiDAR':'Загруженный маршрут · движение поезда — пример, не измеренная позиция';fit();updateTrain();rebuildMarkers();}
 function reset(){const control=[new THREE.Vector3(0,0,0),new THREE.Vector3(500,0,-7),new THREE.Vector3(1000,230,-12),new THREE.Vector3(1450,440,-3),new THREE.Vector3(1950,160,14),new THREE.Vector3(2350,-270,5),new THREE.Vector3(2900,-350,-9),new THREE.Vector3(3450,-30,0)];const spline=new THREE.CatmullRomCurve3(control);build(spline.getSpacedPoints(850),true);$('mapStatus').textContent='Наглядный пример: тоннель, станции и повороты. Положение не вычисляется по LiDAR.';}
 function updateTrain(){if(!route)return;const p=route.getPoint(progress),t=route.getTangent(progress);train.position.copy(p);train.rotation.z=Math.atan2(t.y,t.x);$('routePosition').textContent=(progress*length/1000).toFixed(2);$('mapProgress').value=Math.round(progress*1000);
  let turn=null;for(let ahead=25;ahead<=400;ahead+=25){const u=Math.min(1,progress+ahead/length),v=route.getTangent(u);const angle=Math.atan2(t.x*v.y-t.y*v.x,t.x*v.x+t.y*v.y);if(Math.abs(angle)>.1){turn={ahead,angle};break;}}
  $('nextTurn').textContent=turn?(turn.angle>0?'↶ Поворот влево':'↷ Поворот вправо'):'→ Прямой участок';$('turnDistance').textContent=turn?`примерно через ${turn.ahead} м · по схеме`:'в пределах ближайших 400 м';const station=stations.find(v=>v.p>progress);$('nextStation').textContent=station?.name||'Конец маршрута';$('stationDistance').textContent=`${Math.max(0,((station?.p??1)-progress)*length).toFixed(0)} м · условная позиция`;
  if(follow){controls.target.lerp(p,.08);const target=p.clone().add(flat?new THREE.Vector3(0,-.1,600):new THREE.Vector3(-250,-400,400));camera.position.lerp(target,.04);}}
 function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.1);last=now;if($('map-panel').hidden)return;if(running&&route){progress=Math.min(1,progress+dt*(Number($('demoSpeed').value)/3.6)/length);if(progress===1){running=false;$('demoPlay').textContent='↺ Запустить снова';}}updateTrain();controls.update();renderer.render(scene,camera);updateMarkers();}requestAnimationFrame(frame);
 new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);}).observe(view);
 $('map3d').onclick=()=>{flat=false;controls.enableRotate=true;$('map3d').classList.add('active');$('map2d').classList.remove('active');fit();};$('map2d').onclick=()=>{flat=true;controls.enableRotate=false;$('map2d').classList.add('active');$('map3d').classList.remove('active');fit();};$('mapFit').onclick=()=>{follow=false;$('mapFollow').classList.remove('active');fit();};$('mapFollow').onclick=()=>{follow=!follow;$('mapFollow').classList.toggle('active',follow);};$('demoPlay').onclick=()=>{if(progress===1)progress=0;running=!running;$('demoPlay').textContent=running?'Ⅱ Пауза':'▶ Запустить пример';};$('demoSpeed').oninput=()=>{$('demoSpeedValue').textContent=$('demoSpeed').value+' км/ч';};$('mapProgress').oninput=()=>{progress=Number($('mapProgress').value)/1000;updateTrain();};$('resetMap').onclick=reset;
 $('loadMap').onclick=()=>$('mapFile').click();$('mapFile').onchange=async()=>{const file=$('mapFile').files[0];if(!file)return;try{$('mapStatus').textContent='Чтение карты…';const r=await fetch('/api/map?name='+encodeURIComponent(file.name),{method:'POST',body:file});const data=await r.json();if(!r.ok)throw Error(data.error);if(data.kind==='route')build(data.points.map(p=>new THREE.Vector3(...p)),false);else{disposeGroup();route=null;demo=false;rebuildMarkers();running=false;train.visible=false;$('demoPlay').disabled=true;$('mapProgress').disabled=true;const positions=new Float32Array(data.points.flat());const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));geometryGroup.add(new THREE.Points(g,new THREE.PointsMaterial({color:0x6edbc8,size:2,sizeAttenuation:false})));fit();$('mapBadge').textContent='3D-КАРТА · ПОЗИЦИЯ НЕИЗВЕСТНА';$('mapCaption').textContent='Загружено облако карты; линия маршрута и локализация не заданы';$('routePosition').textContent='—';$('nextStation').textContent='—';$('nextTurn').textContent='Маршрут не задан';$('turnDistance').textContent='';$('stationDistance').textContent='';}$('mapStatus').textContent=file.name+' · '+data.points.length.toLocaleString('ru')+' точек · '+data.note;}catch(e){$('mapStatus').textContent='Ошибка: '+e.message;}finally{$('mapFile').value='';}};
 reset();refreshEvents();
}
