import {setupMap} from '/map.js';
import {openInspection} from '/inspection.js';
const $=id=>document.getElementById(id);
const tabButtons=[...document.querySelectorAll('[data-tab]')];let mapReady=false,historyOffset=0,historyTotal=0;
function tab(name){for(const button of tabButtons)button.classList.toggle('active',button.dataset.tab===name);for(const panel of document.querySelectorAll('.tab-panel'))panel.hidden=panel.id!==name+'-panel';if(name==='map'){if(!mapReady){setupMap();mapReady=true;}else emit('metro-map-refresh');}if(name==='analytics')refreshHistory();}
for(const button of tabButtons)button.onclick=()=>tab(button.dataset.tab);
async function json(url,body){const response=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data;}
function emit(name,detail={}){window.dispatchEvent(new CustomEvent(name,{detail}));}
$('uploadCloud').onclick=()=>$('cloudFile').click();$('cloudFile').onchange=async()=>{const file=$('cloudFile').files[0];if(!file)return;try{$('sourceStatus').textContent='Загрузка '+file.name+'…';$('uploadCloud').disabled=true;const r=await fetch('/api/upload?name='+encodeURIComponent(file.name),{method:'POST',body:file});const data=await r.json();if(!r.ok)throw Error(data.error);await json('/api/live/stop',{});emit('metro-source',{dataset:data.dataset});$('sourceStatus').textContent=file.name;}catch(e){$('sourceStatus').textContent='Ошибка: '+e.message;}finally{$('uploadCloud').disabled=false;$('cloudFile').value='';}};
$('connectSource').onclick=()=>{$('sourceDialog').hidden=false;};$('closeSource').onclick=()=>{$('sourceDialog').hidden=true;};$('sourceDialog').onclick=e=>{if(e.target===$('sourceDialog'))$('sourceDialog').hidden=true;};
$('sourceKind').onchange=()=>{const kind=$('sourceKind').value;$('pathLabel').hidden=kind==='ros';$('inspectBag').hidden=kind!=='bag';$('bagRate').parentElement.hidden=kind!=='bag';$('sourceTopic').parentElement.hidden=kind==='folder';};
$('inspectBag').onclick=async()=>{try{$('sourceError').textContent='Чтение списка топиков…';const data=await json('/api/bag/info',{path:$('sourcePath').value});$('bagTopics').replaceChildren();for(const t of data.topics){const o=document.createElement('option');o.value=t.topic;o.label=t.frames+' сообщений';$('bagTopics').appendChild(o);}if(data.topics.length===1)$('sourceTopic').value=data.topics[0].topic;$('sourceError').textContent=data.topics.length?data.topics.map(t=>t.topic+' · '+t.frames+' кадров').join(' / '):'PointCloud2 не найден. Нужен bag с облаками, а не сырыми пакетами лидара.';}catch(e){$('sourceError').textContent=e.message;}};
$('startSource').onclick=async()=>{try{$('startSource').disabled=true;const kind=$('sourceKind').value;if(kind==='folder'){const data=await json('/api/source',{path:$('sourcePath').value});await json('/api/live/stop',{});emit('metro-source',{dataset:data.dataset});}else{await json('/api/live/start',{kind,path:$('sourcePath').value,topic:$('sourceTopic').value,rate:Number($('bagRate').value)});emit('metro-source',{live:true});}$('sourceDialog').hidden=true;$('sourceError').textContent='';}catch(e){$('sourceError').textContent=e.message;}finally{$('startSource').disabled=false;}};
$('stopSource').onclick=async()=>{try{await json('/api/live/stop',{});emit('metro-stop');$('sourceError').textContent='Поток остановлен';}catch(e){$('sourceError').textContent=e.message;}};
function filters(){const q=new URLSearchParams();if($('historySource').value)q.set('source',$('historySource').value);if($('historyVerdict').value)q.set('verdict',$('historyVerdict').value);if($('historyOnlyConfirmed').checked)q.set('confirmed','1');return q;}
const verdicts={unreviewed:'Не проверено',true:'Верное',false:'Ложное'};
async function refreshHistory(){try{const query=filters();query.set('offset',historyOffset);query.set('limit','50');const data=await json('/api/history?'+query);historyTotal=data.totals.total;$('historyTotal').textContent=historyTotal.toLocaleString('ru');$('historyConfirmed').textContent=data.totals.confirmed||0;$('historyFalse').textContent=data.totals.false_count||0;$('historyNearest').textContent=data.totals.nearest===null?'—':data.totals.nearest.toFixed(1)+' м';const chosen=$('historySource').value;$('historySource').replaceChildren(new Option('Все источники',''));for(const s of data.sources)$('historySource').add(new Option(s,s));$('historySource').value=chosen;
 $('historyRows').replaceChildren();for(const row of data.rows){const tr=document.createElement('tr');for(const value of [new Date(row.recorded_at*1000).toLocaleString('ru'),row.source+' / '+(row.frame??'поток'),row.distance.toFixed(2)+' м',row.mode==='confirmed'?'2 из 3':row.confirmed?'1 облако · подтверждён':'1 облако',verdicts[row.verdict]]){const td=document.createElement('td');td.textContent=value;tr.appendChild(td);}const td=document.createElement('td'),b=document.createElement('button');b.textContent='Подробнее';b.onclick=()=>detail(row.id);td.className='history-actions';const view=document.createElement('button');view.className='primary';view.textContent='Смотреть в 3D';view.onclick=()=>openInspection(row.id);td.append(view,b);tr.appendChild(td);$('historyRows').appendChild(tr);}if(!data.rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.textContent='Пока нет сохранённых тревог по этому фильтру. Откройте облако с препятствием или подключите поток.';tr.appendChild(td);$('historyRows').appendChild(tr);}
 $('historyHistogram').replaceChildren();const max=Math.max(1,...data.histogram.map(b=>b.count));for(const b of data.histogram){const col=document.createElement('div');col.className='hist-col';col.title=`${b.start_m}–${b.start_m+25} м: ${b.count} кадров`;const bar=document.createElement('div');bar.style.height=Math.max(3,b.count/max*100)+'px';const n=document.createElement('b');n.textContent=b.count;const label=document.createElement('span');label.textContent=b.start_m+'–'+(b.start_m+25);col.append(n,bar,label);$('historyHistogram').appendChild(col);}if(!data.histogram.length)$('historyHistogram').textContent='Распределение появится после первой тревоги';$('historyPage').textContent=historyTotal?`${historyOffset+1}–${Math.min(historyOffset+50,historyTotal)} из ${historyTotal}`:'0 записей';$('historyPrev').disabled=historyOffset===0;$('historyNext').disabled=historyOffset+50>=historyTotal;
 }catch(e){$('historyMessage').textContent=e.message;}}
async function detail(id){try{const item=await json('/api/history/item?id='+id),host=$('historyDetail');host.replaceChildren();const h=document.createElement('h2');h.textContent=item.distance.toFixed(2)+' м';host.appendChild(h);const p=document.createElement('p');p.textContent=item.source+' · кадр '+(item.frame??'поток')+' · '+item.result.objects.filter(o=>o.supported).length+' поддержанных объектов';host.appendChild(p);const view=document.createElement('button');view.className='primary';view.textContent='Смотреть в 3D';view.onclick=()=>openInspection(id);host.appendChild(view);const caption=document.createElement('p');caption.className='sub';caption.textContent='Сохранённый результат. Просмотр исходного кадра запускает текущую версию алгоритма.';host.appendChild(caption);const select=document.createElement('select');for(const [value,label] of Object.entries(verdicts))select.add(new Option(label,value));select.value=item.verdict;select.setAttribute('aria-label','Оценка обнаружения');const note=document.createElement('textarea');note.placeholder='Комментарий к обнаружению';note.value=item.note;note.maxLength=2000;const save=document.createElement('button');save.className='primary';save.textContent='Сохранить оценку';save.onclick=async()=>{await json('/api/history/review',{id,verdict:select.value,note:note.value});save.textContent='Сохранено';refreshHistory();};host.append(select,note,save);if(item.dataset_id!==null&&item.frame!==null){const open=document.createElement('button');open.textContent='Открыть исходный кадр';open.onclick=()=>{tab('detection');emit('metro-open-frame',{dataset:item.dataset_id,frame:item.frame});};host.appendChild(open);}const exportButton=document.createElement('button');exportButton.textContent='Скачать сохранённый JSON';exportButton.onclick=()=>download(JSON.stringify(item,null,2),'detection-'+id+'.json','application/json');host.appendChild(exportButton);const pre=document.createElement('pre');pre.textContent=JSON.stringify({status:item.result.status,mode:item.mode,processing_ms:item.latency,timestamp_ns:item.timestamp_ns,objects:item.result.objects.filter(o=>o.supported).map(o=>({distance_m:o.distance_m,center:o.center,dimensions:o.dimensions,evidence:o.evidence,confirmed:o.confirmed}))},null,2);host.appendChild(pre);}catch(e){$('historyDetail').textContent=e.message;}}
for(const id of ['historySource','historyVerdict','historyOnlyConfirmed'])$(id).onchange=()=>{historyOffset=0;refreshHistory();};$('refreshHistory').onclick=refreshHistory;$('historyPrev').onclick=()=>{historyOffset=Math.max(0,historyOffset-50);refreshHistory();};$('historyNext').onclick=()=>{historyOffset+=50;refreshHistory();};$('historyExport').onclick=async()=>{try{const r=await fetch('/api/history/csv?'+filters());if(!r.ok)throw Error('Ошибка выгрузки');download(await r.text(),'detection-history.csv','text/csv;charset=utf-8');}catch(e){$('historyMessage').textContent=e.message;}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('downloadGuide').onclick=async()=>{const r=await fetch('/QUICKSTART.md');download(await r.text(),'METRO-QUICKSTART.md','text/markdown;charset=utf-8');};$('loadConfig').onclick=()=>$('configFile').click();$('configFile').onchange=async()=>{try{const file=$('configFile').files[0];if(!file)return;await json('/api/config',JSON.parse(await file.text()));emit('metro-config');tab('detection');}catch(e){alert('Конфигурация не загружена: '+e.message);}finally{$('configFile').value='';}};
